return {
  dir = vim.fn.stdpath 'config',
  name = 'pr-pilot',
  cmd = {
    'PRCreate',
    'PRIssue',
    'PRPR',
    'PRPreview',
    'PRDiff',
    'PRSearch',
  },
  keys = {
    { '<leader>prc', desc = 'PR: Create issue + PR' },
    { '<leader>pri', desc = 'PR: Create issue only' },
    { '<leader>prr', desc = 'PR: Create PR only' },
    { '<leader>prp', desc = 'PR: Preview (dry-run)' },
    { '<leader>prd', desc = 'PR: Show git diff' },
    { '<leader>prs', desc = 'PR: Search Jira tickets' },
  },
  config = function()
    require('custom.pr-pilot').setup {
      binary_path = 'pr-pilot',
      keymaps = true,
      repos = {
        'darioastete/PR-Pilot',
        'darioastete/ecultiva-erp-frontend',
        'darioastete/ecultiva-erp-backend',
        '309-Technology/hvac-ai-api',
        '309-Technology/infrastructure',
        '309-Technology/hvac-admin-panel-backend',
        '309-Technology/hvac-admin-panel-front',
        'darioastete/309-admin-panel',
        'Jeanpierre2913/Curso-Next',
        'darioastete/309-administration-ms',
        '309-Technology/hvac-landing',
        '309-Technology/309-website',
        'darioastete/kickstart-dario.nvim',
        '309-Technology/ai-workflow-db',
        'darioastete/309-design-system',
        'darioastete/309-profile-verification-service',
        '309-Technology/kmm_base',
        '309-Technology/kmm_ios',
        '309-Technology/kmm_android',
        'darioastete/obsidian-notes',
        '309-Technology/HVAC-AI',
        'darioastete/ecultiva-landing',
        'aleolayar0104/administration-service',
        '309-Technology/HVACAI-Backend-AIO',
        '309-Technology/hvac-label-detection',
        '309-Technology/HVAC-backend-payment',
        '309-Technology/hvac-ai-embeddings',
        '309-Technology/309-notify-microservice',
        '309-Technology/arcore-android',
        '309-Technology/alcosi-identity-server-communication-error-parser',
        '309-Technology/alcosi-identity-server-communication',
        '309-Technology/backend-api-gateway',
        '309-Technology/web-platform',
        '309-Technology/email-sender',
        'darioastete/bruno-api-tests',
        '309-Technology/hvac-admin-api',
        '309-Technology/309-identity-microservice',
        '309-Technology/309-documents-microservice',
        '309-Technology/iOS-DL',
        'darioastete/docs',
        '309-Technology/bitrix24',
        '309-Technology/basic-tools',
        '309-Technology/alcosi-notification-service-communication',
        '309-Technology/alcosi-template-service-communication',
        '309-Technology/alcosi-blockchain-api-gateway',
        '309-Technology/twinhorn',
        '309-Technology/alcosi-commons-library',
        '309-Technology/twinfaces',
        '309-Technology/twins',
        '309-Technology/landing',
        '309-Technology/cvat',
        '309-Technology/backend-report',
        '309-Technology/backend-profile',
        '309-Technology/backend-dataset',
        '309-Technology/aux-microservices',
        '309-Technology/android',
        'darioastete/music-store-admin',
        'darioastete/store-backend-nest',
        '309-Technology/hvac-admin',
        '309-Technology/iOS',
        '309-Technology/ai-hvac-type-classifier',
        '309-Technology/hvac-ai-server',
        '309-Technology/ai-hvac-rtu-side-classifier',
        'darioastete/platform-cubebox',
        '309-Technology/ui-kit-core',
        'SynaptecCorp/sipan-laravel10-vue3-tailwind',
        '309-Technology/ai-hvac-nameplate-focus',
        'darioastete/ecultiva',
        'darioastete/music-store',
        '309-Technology/labelstudio-server',
        'darioastete/financial-personal',
        '309-Technology/hvac-admin-doc',
        'darioastete/loopcopilot-waitlist',
        'darioastete/309technology-admin-api',
        'darioastete/bot-eats',
        'darioastete/jira-discord-middleware',
        'darioastete/Digital-Menu',
        'darioastete/astrocommunity',
        'darioastete/excel-bot-temp',
        '309-Technology/nft-akc-staking-backend',
        'darioastete/landing-challenge',
        'darioastete/sipan-hospedaje-astro-vue',
        'darioastete/boilerplate-astro-pwa',
        'alainspp/App-HospedajeSipan',
        'darioastete/My-portfolio',
        'darioastete/schedule-app',
        'darioastete/myfinance',
        'darioastete/djstore_backend_nestjs',
        'darioastete/config-nvchad',
        'darioastete/MoneyManager',
        'SynaptecCorp/bot-logic',
        'darioastete/alegra-challenge',
        'darioastete/scanner-qr-app',
        'darioastete/Astro-PWA',
        'SynaptecCorp/pm-pwa-vue3',
        'darioastete/front-sipan-modular',
        'darioastete/PagosRecargasTestVite',
        'darioastete/PagosRecargasFrontendTest',
        'darioastete/challengue-angular',
        'darioastete/sbh_erp',
      },
    }
  end,
}
